package com.example.ui.editor.theme

import androidx.compose.ui.graphics.Color

enum class EditorThemeType(
    val displayName: String,
    val isDark: Boolean,
    val background: Color,
    val surface: Color,
    val lineNumbersBg: Color,
    val lineNumbersText: Color,
    val textColor: Color,
    val cursorColor: Color,
    val activeLineColor: Color,
    val tagColor: Color,
    val attributeColor: Color,
    val stringColor: Color,
    val keywordColor: Color,
    val commentColor: Color,
    val numberColor: Color,
    val selectorColor: Color,
    val propertyColor: Color
) {
    VS_CODE_DARK(
        displayName = "VS Code Dark",
        isDark = true,
        background = Color(0xFF1E1E1E),
        surface = Color(0xFF252526),
        lineNumbersBg = Color(0xFF1E1E1E),
        lineNumbersText = Color(0xFF858585),
        textColor = Color(0xFFD4D4D4),
        cursorColor = Color(0xFF569CD6),
        activeLineColor = Color(0xFF2A2D2E),
        tagColor = Color(0xFF569CD6),
        attributeColor = Color(0xFF9CDCFE),
        stringColor = Color(0xFFCE9178),
        keywordColor = Color(0xFFC586C0),
        commentColor = Color(0xFF6A9955),
        numberColor = Color(0xFFB5CEA8),
        selectorColor = Color(0xFFD7BA7D),
        propertyColor = Color(0xFF9CDCFE)
    ),
    MONOKAI(
        displayName = "Monokai Pro",
        isDark = true,
        background = Color(0xFF272822),
        surface = Color(0xFF383830),
        lineNumbersBg = Color(0xFF272822),
        lineNumbersText = Color(0xFF75715E),
        textColor = Color(0xFFF8F8F2),
        cursorColor = Color(0xFFF92672),
        activeLineColor = Color(0xFF3E3D32),
        tagColor = Color(0xFFF92672),
        attributeColor = Color(0xFFA6E22E),
        stringColor = Color(0xFFE6DB74),
        keywordColor = Color(0xFF66D9EF),
        commentColor = Color(0xFF75715E),
        numberColor = Color(0xFFAE81FF),
        selectorColor = Color(0xFFA6E22E),
        propertyColor = Color(0xFF66D9EF)
    ),
    DRACULA(
        displayName = "Dracula",
        isDark = true,
        background = Color(0xFF282A36),
        surface = Color(0xFF343746),
        lineNumbersBg = Color(0xFF282A36),
        lineNumbersText = Color(0xFF6272A4),
        textColor = Color(0xFFF8F8F2),
        cursorColor = Color(0xFFFF79C6),
        activeLineColor = Color(0xFF44475A),
        tagColor = Color(0xFFFF79C6),
        attributeColor = Color(0xFF50FA7B),
        stringColor = Color(0xFFF1FA8C),
        keywordColor = Color(0xFFBD93F9),
        commentColor = Color(0xFF6272A4),
        numberColor = Color(0xFFBD93F9),
        selectorColor = Color(0xFF50FA7B),
        propertyColor = Color(0xFF8BE9FD)
    ),
    CYBERPUNK(
        displayName = "Cyberpunk Neon",
        isDark = true,
        background = Color(0xFF0D0F18),
        surface = Color(0xFF161A29),
        lineNumbersBg = Color(0xFF0D0F18),
        lineNumbersText = Color(0xFF4B5563),
        textColor = Color(0xFFE2E8F0),
        cursorColor = Color(0xFF00F0FF),
        activeLineColor = Color(0xFF1E2235),
        tagColor = Color(0xFFFF007F),
        attributeColor = Color(0xFF00F0FF),
        stringColor = Color(0xFFFFE600),
        keywordColor = Color(0xFF76FF03),
        commentColor = Color(0xFF64748B),
        numberColor = Color(0xFFFF7700),
        selectorColor = Color(0xFF00F0FF),
        propertyColor = Color(0xFFFF007F)
    ),
    NORD(
        displayName = "Nord Frost",
        isDark = true,
        background = Color(0xFF2E3440),
        surface = Color(0xFF3B4252),
        lineNumbersBg = Color(0xFF2E3440),
        lineNumbersText = Color(0xFF4C566A),
        textColor = Color(0xFFD8DEE9),
        cursorColor = Color(0xFF88C0D0),
        activeLineColor = Color(0xFF434C5E),
        tagColor = Color(0xFF81A1C1),
        attributeColor = Color(0xFF8FBCBB),
        stringColor = Color(0xFFA3BE8C),
        keywordColor = Color(0xFFB48EAD),
        commentColor = Color(0xFF4C566A),
        numberColor = Color(0xFFB48EAD),
        selectorColor = Color(0xFF88C0D0),
        propertyColor = Color(0xFFD08770)
    ),
    GITHUB_LIGHT(
        displayName = "GitHub Light",
        isDark = false,
        background = Color(0xFFFFFFFF),
        surface = Color(0xFFF6F8FA),
        lineNumbersBg = Color(0xFFFFFFFF),
        lineNumbersText = Color(0xFF959DA5),
        textColor = Color(0xFF24292E),
        cursorColor = Color(0xFF0366D6),
        activeLineColor = Color(0xFFF1F8FF),
        tagColor = Color(0xFF22863A),
        attributeColor = Color(0xFF6F42C1),
        stringColor = Color(0xFF032F62),
        keywordColor = Color(0xFFD73A49),
        commentColor = Color(0xFF6A737D),
        numberColor = Color(0xFF005CC5),
        selectorColor = Color(0xFF6F42C1),
        propertyColor = Color(0xFF005CC5)
    ),
    SOLARIZED_LIGHT(
        displayName = "Solarized Light",
        isDark = false,
        background = Color(0xFFFDF6E3),
        surface = Color(0xFFEEE8D5),
        lineNumbersBg = Color(0xFFFDF6E3),
        lineNumbersText = Color(0xFF93A1A1),
        textColor = Color(0xFF657B83),
        cursorColor = Color(0xFF268BD2),
        activeLineColor = Color(0xFFEEE8D5),
        tagColor = Color(0xFF268BD2),
        attributeColor = Color(0xFFB58900),
        stringColor = Color(0xFF2AA198),
        keywordColor = Color(0xFF859900),
        commentColor = Color(0xFF93A1A1),
        numberColor = Color(0xFFD33682),
        selectorColor = Color(0xFFB58900),
        propertyColor = Color(0xFFCB4B16)
    ),
    ONE_LIGHT(
        displayName = "One Light",
        isDark = false,
        background = Color(0xFFFAFAFA),
        surface = Color(0xFFEAEAEB),
        lineNumbersBg = Color(0xFFFAFAFA),
        lineNumbersText = Color(0xFFA0A1A7),
        textColor = Color(0xFF383A42),
        cursorColor = Color(0xFF526FFF),
        activeLineColor = Color(0xFFF0F0F1),
        tagColor = Color(0xFFE45649),
        attributeColor = Color(0xFF986801),
        stringColor = Color(0xFF50A14F),
        keywordColor = Color(0xFFA626A4),
        commentColor = Color(0xFFA0A1A7),
        numberColor = Color(0xFF986801),
        selectorColor = Color(0xFF4078F2),
        propertyColor = Color(0xFFE45649)
    )
}
